#!/bin/sh
exec tail -n +3 $0

menuentry "Install Centos 7 server amd64" {
    set bootdir="/images/centos/7/amd64"
    set confdir="/s__srv_name__"
    linux (tftp)$bootdir/vmlinuz inst.ks=http://10.0.222.1$confdir/s__srv_name__.seed
    initrd (tftp)$bootdir/initrd.img
}

